In [2]:
from numpy import array
from numpy.linalg import lstsq

# Data points
x = array([-1, 0, 1])
y = array([3.1, 0.9, 2.9])

# Creating the matrix A for Ax = B
A = array([x**2, [1, 1, 1]]).T

# Using least squares to solve for a and b
coefficients, _, _, _ = lstsq(A, y, rcond=None)
a, b = coefficients

a, b
A


array([[1, 1],
       [0, 1],
       [1, 1]])

In [4]:
def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

def multiply_matrices(A, B):
    result = [[sum(a * b for a, b in zip(A_row, B_col)) for B_col in zip(*B)] for A_row in A]
    return result

def inverse(matrix):
    # This function computes the inverse of a 2x2 matrix.
    # It's a simplified version, works only for 2x2 matrices.
    det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    if det == 0:
        raise ValueError("Matrix is not invertible")
    return [[matrix[1][1] / det, -matrix[0][1] / det], [-matrix[1][0] / det, matrix[0][0] / det]]

# Data and matrices
A = [[1, 1], [0, 1], [1, 1]]
B = [[3.1], [0.9], [2.9]]

# Least Squares computation
A_T = transpose(A)
A_TA = multiply_matrices(A_T, A)
A_TB = multiply_matrices(A_T, B)
inv_A_TA = inverse(A_TA)
x = multiply_matrices(inv_A_TA, A_TB)

# Extracting coefficients a and b
a, b = x[0][0], x[1][0]

print(f"a = {a}, b = {b}")
print("A_T =", A_T)
print("A_TA =", A_TA)
print("A_TB =", A_TB)
print("inv_A_TA =", inv_A_TA)
print("x =", x)


a = 2.0999999999999996, b = 0.9000000000000004
A_T = [[1, 0, 1], [1, 1, 1]]
A_TA = [[2, 2], [2, 3]]
A_TB = [[6.0], [6.9]]
inv_A_TA = [[1.5, -1.0], [-1.0, 1.0]]
x = [[2.0999999999999996], [0.9000000000000004]]


In [9]:
# Define the transpose function
def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

# Define the function for matrix multiplication
def multiply_matrices(A, B):
    return [[sum(a * b for a, b in zip(A_row, B_col)) for B_col in zip(*B)] for A_row in A]

# Define the function for finding the inverse of a 2x2 matrix
def inverse(matrix):
    det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    if det == 0:
        raise ValueError("Matrix is not invertible")
    return [[matrix[1][1] / det, -matrix[0][1] / det], [-matrix[1][0] / det, matrix[0][0] / det]]

# Data points
x_values = [1, 2, 3, 4]
y_values = [0, 1, 1, 2]

# Creating the matrix A and vector B
A = [[x, 1] for x in x_values]  # Matrix A with columns for x^1 and x^0 (constant)
B = [[y] for y in y_values]     # Vector B with y-values

# Calculating A_T, A_TA, A_TB, inv_A_TA, and x
A_T = transpose(A)                     # Transpose of A
A_TA = multiply_matrices(A_T, A)       # A_T multiplied by A
A_TB = multiply_matrices(A_T, B)       # A_T multiplied by B
inv_A_TA = inverse(A_TA)               # Inverse of A_TA
x = multiply_matrices(inv_A_TA, A_TB)  # Final result: inv(A_TA) multiplied by A_TB

# Extracting coefficients a and b
a, b = x[0][0], x[1][0]

# Print each step and the result
print("Matrix A:", A)
print("Vector B:", B)
print("Transpose of A (A_T):", A_T)
print("A_T multiplied by A (A_TA):", A_TA)
print("A_T multiplied by B (A_TB):", A_TB)
print("Inverse of A_TA (inv_A_TA):", inv_A_TA)
print("Solution (x):", x)
print(f"Best fitting line: y = {a}x + {b}")


Matrix A: [[1, 1, 1], [1, 2, 4], [1, 3, 9], [1, 4, 16], [1, 5, 25], [1, 6, 36], [1, 7, 49]]
Vector B: [[2.31], [2.01], [1.8], [1.66], [1.55], [1.47], [1.41]]
Transpose of A (A_T): [[1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7], [1, 4, 9, 16, 25, 36, 49]]
A_T multiplied by A (A_TA): [[7, 28, 140], [28, 140, 784], [140, 784, 4676]]
A_T multiplied by B (A_TB): [[12.21], [44.809999999999995], [213.87]]
Inverse of A_TA (inv_A_TA): [[0.7142857142857143, -0.14285714285714285], [-0.14285714285714285, 0.03571428571428571]]
Solution (x): [[2.320000000000001], [-0.14392857142857163]]
Best fitting line: y = 2.320000000000001x + -0.14392857142857163


In [13]:
import numpy as np

# Data points
T_values = np.array([1, 2, 3, 4, 5, 6, 7])
V_values = np.array([2.31, 2.01, 1.80, 1.66, 1.55, 1.47, 1.41])

# Creating the matrix A (coefficient matrix) and vector B
A = np.column_stack((np.ones(len(T_values)), T_values, T_values**2))
B = V_values.reshape(-1, 1)

# Calculating intermediate matrices
A_T = A.T
A_TA = A_T @ A
A_TB = A_T @ B
inv_A_TA = np.linalg.inv(A_TA)

# Solution for x (coefficients a, b, c)
x = inv_A_TA @ A_TB

# Extracting coefficients a, b, and c
a, b, c = x.flatten()

# Print the intermediate matrices and the result
print("Matrix A:\n", A)
print("Vector B:\n", B)
print("Transpose of A (A_T):\n", A_T)
print("A_T multiplied by A (A_TA):\n", A_TA)
print("A_T multiplied by B (A_TB):\n", A_TB)
print("Inverse of A_TA (inv_A_TA):\n", inv_A_TA)
print("Solution (x):\n", x)
print(f"Best fitting curve: V = {a} + {b}T + {c}T^2")



Matrix A:
 [[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]
 [ 1.  6. 36.]
 [ 1.  7. 49.]]
Vector B:
 [[2.31]
 [2.01]
 [1.8 ]
 [1.66]
 [1.55]
 [1.47]
 [1.41]]
Transpose of A (A_T):
 [[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  2.  3.  4.  5.  6.  7.]
 [ 1.  4.  9. 16. 25. 36. 49.]]
A_T multiplied by A (A_TA):
 [[   7.   28.  140.]
 [  28.  140.  784.]
 [ 140.  784. 4676.]]
A_T multiplied by B (A_TB):
 [[ 12.21]
 [ 44.81]
 [213.87]]
Inverse of A_TA (inv_A_TA):
 [[ 2.42857143 -1.28571429  0.14285714]
 [-1.28571429  0.79761905 -0.0952381 ]
 [ 0.14285714 -0.0952381   0.01190476]]
Solution (x):
 [[ 2.59285714]
 [-0.32583333]
 [ 0.0227381 ]]
Best fitting curve: V = 2.5928571428571656 + -0.32583333333334014T + 0.02273809523809533T^2


In [14]:
import numpy as np

# Data points
x_values = np.array([-1, -0.5, 0, 0.5, 1])
y_values = np.array([-1, 0, 1, 2, 1])

# Creating the matrix A (coefficient matrix) and vector B
A = np.column_stack((np.sin(np.pi * x_values), np.cos(np.pi * x_values)))
B = y_values.reshape(-1, 1)

# Calculating intermediate matrices
A_T = A.T
A_TA = A_T @ A
A_TB = A_T @ B
inv_A_TA = np.linalg.inv(A_TA)

# Solution for x (coefficients a, b)
x = inv_A_TA @ A_TB

# Extracting coefficients a and b
a, b = x.flatten()

# Print the intermediate matrices and the result
print("Matrix A:\n", A)
print("Vector B:\n", B)
print("Transpose of A (A_T):\n", A_T)
print("A_T multiplied by A (A_TA):\n", A_TA)
print("A_T multiplied by B (A_TB):\n", A_TB)
print("Inverse of A_TA (inv_A_TA):\n", inv_A_TA)
print("Solution (x):\n", x)
print(f"Best fitting curve: f(x) = {a} * sin(pi * x) + {b} * cos(pi * x)")


Matrix A:
 [[-1.2246468e-16 -1.0000000e+00]
 [-1.0000000e+00  6.1232340e-17]
 [ 0.0000000e+00  1.0000000e+00]
 [ 1.0000000e+00  6.1232340e-17]
 [ 1.2246468e-16 -1.0000000e+00]]
Vector B:
 [[-1]
 [ 0]
 [ 1]
 [ 2]
 [ 1]]
Transpose of A (A_T):
 [[-1.2246468e-16 -1.0000000e+00  0.0000000e+00  1.0000000e+00
   1.2246468e-16]
 [-1.0000000e+00  6.1232340e-17  1.0000000e+00  6.1232340e-17
  -1.0000000e+00]]
A_T multiplied by A (A_TA):
 [[2. 0.]
 [0. 3.]]
A_T multiplied by B (A_TB):
 [[2.]
 [1.]]
Inverse of A_TA (inv_A_TA):
 [[0.5        0.        ]
 [0.         0.33333333]]
Solution (x):
 [[1.        ]
 [0.33333333]]
Best fitting curve: f(x) = 1.0 * sin(pi * x) + 0.3333333333333333 * cos(pi * x)
